import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateTicketPDF = (booking, temple) => {
  const doc = new jsPDF();
  
  // Colors & Styles
  const primaryColor = [180, 83, 9]; // Saffron
  const darkColor = [63, 39, 14]; // Dark Brown
  
  // Header Background
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('DarshanEase E-Ticket', 105, 25, { align: 'center' });
  
  // Temple Info
  doc.setTextColor(...darkColor);
  doc.setFontSize(16);
  doc.text(temple.name, 20, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`${temple.city}, ${temple.state}`, 20, 62);
  
  // Booking Details Section
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 70, 190, 70);
  
  doc.setFontSize(12);
  doc.setTextColor(...darkColor);
  doc.setFont('helvetica', 'bold');
  doc.text('Booking Information', 20, 80);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  const slotDate = new Date(booking.slotId?.date).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });
  
  doc.text(`Ticket Number: ${booking.ticketNumber}`, 20, 90);
  doc.text(`Darshan Type: ${booking.slotId?.darshanType || 'General'}`, 20, 98);
  doc.text(`Date: ${slotDate}`, 20, 106);
  doc.text(`Time: ${booking.slotId?.startTime} - ${booking.slotId?.endTime}`, 20, 114);
  doc.text(`No. of Persons: ${booking.noOfPersons}`, 20, 122);
  doc.text(`Total Paid: INR ${booking.totalAmount}`, 20, 130);
  
  // QR Code (If data URL exists)
  if (booking.qrCodeUrl) {
    doc.addImage(booking.qrCodeUrl, 'PNG', 140, 75, 50, 50);
  }
  
  // Devotee Details Table
  doc.text('Devotee Details:', 20, 145);
  const devoteeBody = booking.devoteeDetails?.map((d, i) => [
    i + 1,
    d.name,
    d.age,
    d.gender,
    d.idProof
  ]) || [];
  
  doc.autoTable({
    startY: 150,
    head: [['#', 'Name', 'Age', 'Gender', 'ID Proof']],
    body: devoteeBody,
    theme: 'grid',
    headStyles: { fillColor: primaryColor },
    margin: { left: 20, right: 20 }
  });
  
  // Instructions
  const finalY = doc.lastAutoTable.finalY || 150;
  doc.setFont('helvetica', 'bold');
  doc.text('Important Instructions:', 20, finalY + 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  
  const instructions = [
    '1. Please carry a printed copy or digital copy of this ticket.',
    '2. Bring the original ID proofs mentioned in the devotee details.',
    '3. Report at the entrance at least 30 minutes before the slot time.',
    `4. Dress Code: ${temple.dressCode || 'Traditional wear required. No shorts or sleeveless tops.'}`,
    '5. Electronic items, mobile phones, and cameras are strictly prohibited inside the main sanctum.'
  ];
  
  let currentY = finalY + 22;
  instructions.forEach(inst => {
    doc.text(inst, 20, currentY);
    currentY += 6;
  });
  
  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text('Generated by DarshanEase Booking System. For support, visit www.darshanease.com', 105, 285, { align: 'center' });
  
  // Download
  doc.save(`${booking.ticketNumber}_${temple.name.replace(/\s+/g, '_')}.pdf`);
};
